### DISCUSSION TITLE
Input contains unmappable characters: javaslang/?.class

### DISCUSSION THREAD

**Discussion by kioli** [dipien/bye-bye-jetifier#52] [General]
**Describe the bug**
I implemented the plugin like this

```
dependencies {
    classpath("com.dipien:bye-bye-jetifier:1.2.0")
}

subprojects {
    apply plugin: "com.dipien.byebyejetifier"

    byeByeJetifier {
        excludedFilesFromScanning = [
                "org/mockito/android/internal/creation/AndroidTempFileLocator.class"
        ]
    }
}
```

and locally it runs and works properly, but when I add it to my GitLab CI/CD pipeline it fails with the following error

```
Execution failed for task ':myLib:canISayByeByeJetifier'.
> Malformed input or input contains unmappable characters: javaslang/?.class
```

**To Reproduce**
GitLab CI/CD fails at the following (first) step

```
check-jetifier:
  stage: check-jetifier
  image: $ECR_REPOSITORY/$CI_PROJECT_PATH:build-$CI_COMMIT_SHA
  script:
    - ./gradlew canISayByeByeJetifier -Pandroid.enableJetifier=false
```
